### ISSUE TITLE
reply not working yet, saving state here

### ISSUE THREAD

**Issue by 0thernet** [mysterious-technology/threadrip#1]
> FetchError: invalid json response body at https://api.twitter.com/1.1/statuses/update reason: Unexpected token < in JSON at position 0

```
curl "https://api.twitter.com/1.1/statuses/update.json" \
-H "Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAEliGAEAAAAAzgJHdMJcPOxOPzg%2FaLXjIN5bXJI%3DROueNKyDKnjjl1IS616mN0HyjM7OL7NiEKkK6DVEIH0rN4kZ6K" \
--request POST \
--data '{"in_reply_to_status_id": "1297601036534784000","status":"hi"}' \
-H "Content-Type: application/json"
```

**Comment by benzguo** [comment]
Fixed the original error (was missing the `.json` in the url).

Now I'm getting:
```
errors: [
    {
      code: 220,
      message: 'Your credentials do not allow access to this resource.'
    }
  ]
```

**Comment by benzguo** [comment]
### Rate limiting info:
Requests / 3-hour window | 300* per user; 300* per app

**Comment by benzguo** [comment]
new error: `errors: [ { code: 32, message: 'Could not authenticate you.' } ]`

**Comment by benzguo** [comment]
\o/ it works 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/894119/90987369-62b5bf80-e53f-11ea-8742-36ae6e9eca30.png">
