### ISSUE TITLE
Store last tweet ID, use since_id instead of start_time

### ISSUE THREAD

**Issue by 0thernet** [mysterious-technology/threadrip#2]
start_time is too brittle, missing cutoff

since_id *should* work as long as cron runs don't overlap (which I think is guaranteed).

> Returns results with a Tweet ID greater than (that is, more recent than) the specified ID. The ID specified is exclusive and responses will not include it. If included with the same request as a start_time parameter, only since_id will be used.

**Comment by benzguo** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/894119/91155435-b3303880-e677-11ea-8d60-46500b239f1c.png">

output
